etalons:
  - code: 140100
    name: 'ПДВ'
    row: 1
    
  - code: 110200
    name: 'Податок на прибуток (90%)'
    row: 2
    
  - code: 110230
    name: 'в тому числі аванси'
    row: 3
    
  - code: 210100
    name: 'Частина чистого прибутку'
    row: 4
    
  - code: 130200
    name: 'Вода'
    row: 5
    
  - code: 130300
    name: 'Надра (75%)'
    row: 6
    
  - code: 130600
    name: 'Радіочастоти'
    row: 7
    
  - code: 140200
    name: 'Трансопртні засоби'
    row: 8
    
  - code: 210810
    name: 'Пеня у сферi ЗЕД'
    row: 9
    
  - code: 310100
    name: 'Реалізація безх. майна'
    row: 10
    
  - code: 190110
    name: 'Екологiчний податок (20%)'
    row: 11
    
  - code: 110110
    name: 'Військовий збір'
    row: 12
    
  - code: 110130
    name: 'ПДФО (25%)'
    row: 13
    
  - code: 110108
    name: 'в т. ч. ПДФО в виде %'
    row: 14
    
  - code: 240613
    name: 'Iнші'
    row: 15
    
  - code: 110100
    name: 'Податок на доходи'
    row: 16
    
  - code: 130102
    name: 'Лiсовi ресурси'
    row: 17
    
  - code: 180505
    name: 'Фiксований сiльськогосп.'
    row: 18
    
  - code: 180105
    name: 'Земля юр. осіб'
    row: 19
    
  - code: 180106
    name: 'Оренда юр. осіб'
    row: 20
    
  - code: 180107
    name: 'Земля фіз. осіб'
    row: 21
    
  - code: 180109
    name: 'Оренда фіз. осіб'
    row: 22
    
  - code: 110202
    name: 'Податок на прибуток'
    row: 23
    
  - code: 110239
    name: 'в т. ч. прибуток комун.'
    row: 24
    
  - code: 140400
    name: 'Акцизний податок'
    row: 25
    
  - code: 130299
    name: 'Вода'
    row: 26
    
  - code: 130399
    name: 'Надра'
    row: 27
    
  - code: 220100
    name: 'Плата за лiцензiї'
    row: 28
    
  - code: 180501
    name: 'Єдиний з юр. осiб'
    row: 29
    
  - code: 180502
    name: 'Єдиний з фiз. осiб'
    row: 30
    
  - code: 180100
    name: 'Нерух. майно'
    row: 31
    
  - code: 310199
    name: 'Реалізація безх. майна'
    row: 32
    
  - code: 190199
    name: 'Екологiчний податок'
    row: 33
    
  - code: 180110
    name: 'Транспортний податок'
    row: 34
    
  - code: 240600
    name: 'Iнші'
    row: 35

footer:
  # значения для «подвала»
  - code: 210877
    name: 'Адміністративні штрафи'
    row: 1

  - code: 190177
    name: 'Екологічний податок (25%)'
    row: 2

  - code: 110177
    name: 'ПДФО (60%)'
    row: 3