# Суммы, нумерация с 1
# Сумма госбюджет
sums:
  - varname: 'db'
    lines: [1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
    desc: "ДЕРЖАВНИЙ БЮДЖЕТ"


    # Сумма местный бюджет
  - varname: 'mb'
    lines: [16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
    desc: 'МІСЦЕВИЙ БЮДЖЕТ'


    # Сумма земля ю/о
  - varname: 'zu'
    lines: [19,20]
    desc: 'ЗЕМЛЯ ЮР. ОСОБИ'


    # Сумма земля ю/о 
  - varname: 'zf'
    lines: [21,22]
    desc: 'ЗЕМЛЯ ФІЗ. ОСОБИ'


    # Ед. налог 
  - varname: 'ed'
    lines: [29,30]
    desc: 'ЄДИНИЙ ПОДАТОК'


insert:
    # итоги вставляются после, нумерация с 0 
  - line: 14
    varname: 'db'

  - line: 17
    varname: 'zu'

  - line: 19
    varname: 'zf'

  - line: 27
    varname: 'ed'

  - line: 34
    varname: 'mb'

divs:
    # линии ставятся после, нумерация с 0
    # имеющиеся итоги учитывать 
    single: [10,12,17,23,29,32]
    double: [14,38]
    emphasis: [18,21,30]
    italic: [1,12,25]
