tax:
  - row:
    - query:
        rozd: 1
        bd: 0
        rd: '1401'
        pg: '01'
    _code: '140100'
  - row:
    - query:
        rozd: 1
        bd: 0
        rd: '1102'
        pg: '01' 
    - query:
        rozd: 1
        bd: 0
        rd: '1102'
        pg: '31' 
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        coef: 0.90
    - query:
        # возврат авансов
        rozd: 1
        bd: 0
        rd: '1102'
        pg: '40' 
        st: '01'
    _code: '110200'    
  - row:
    - query:
        rozd: 1
        bd: 0
        rd: '1102'
        pg: '31' 
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '33' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '40' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '46' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '41' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '39' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '37' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '36' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '35' 
        coef: 0.90
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        pg: '34' 
        coef: 0.90
    - query:
        # возврат авансов
        rozd: 1
        bd: 0
        rd: '1102'
        pg: "40" 
        st: '01'
    _code: '110230'    
  - row:
    - query:
        rozd: 1
        bd: 0
        rd: '2101'
    _code: '210100'  
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1302'
        coef: 0.50
    _code: '130200'
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1303'
        pg: '01'
        coef: 0.75
    _code: '130300'
  - row:
    - query:
        bd: 0
        rd: '2108'
        pg: '10'
    _code: '210810'
  - row:
    - query:
        bd: 0
        rd: '3101'
    _code: '310100'
  - row:
    - query:
        rozd: 1
        bd: 0
        rd: '1306'
    _code: '130600'
  - row:
    - query:
        bd: 0
        rd: '1402'
        pg: '08'
    _code: '140200'
  - row:
    - query:
        bd: 0
        rd: '2108'
        pg: '09'
    - query:
        bd: 0
        rd: '2108'
        pg: '11'
    - query:
        bd: 0
        rd: '2406'
        pg: '03'
    - query:
        # бывший виноград
        rozd: 1
        bd: 0
        rd: '1906'
    _code: '240613' 
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1901'
        coef: 0.20
    _code: '190110'
  - row:
    # военный сбор
    - query:
        rozd: 1
        bd: 0
        rd: '1101'
        pg: '10'
    _code: '110110'
  - row:
    # НДФЛ 
    - query:
        rozd: 3
        bd: 0
        rd: '1101'
        coef: 0.25
    # НДФЛ в виде %
    - query:
        bd: 0
        rd: '1101'
        pg: '08'
    _code: '110130'
  - row:
    # НДФЛ в виде % отдельно
    - query:
        bd: 0
        rd: '1101'
        pg: '08'
    _code: '110108'
  - row:
    # местный бюджет
    - query:
        rozd: 3
        bd: 0
        rd: '1101'
        coef: 0.75
    _code: '110100'
  - row:
    - query:
        rozd: 1
        bd: 1
        rd: '1301'
        pg: '02' 
    _code: '130102'
  - row:
    # Фіксований сільськогосподарський податок
    - query:
        rozd: 1
        bd: 1
        rd: '1805'
        pg: '05'
    _code: '180505'
  - row:
    # зю з 
    - query:
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '05'
    _code: '180105'
  - row:
    # зю ор
    - query:
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '06'
    _code: '180106'
  - row:
    # зю ор
    - query:
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '07'
    _code: '180107'
  - row:
    # зю ор
    - query:
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '09'
    _code: '180109'
  - row:
    # транспорт
    - query:
        bd: 1
        rd: '1801'
        pg: '10'
    - query:
        bd: 1
        rd: '1801'
        pg: '11'
    _code: '180110'
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1102'
        coef: 0.10
    - query:
        bd: 1
        rd: '1102'
    _code: '110202'
  - row:
    - query:
        rozd: 4
        bd: 1
        rd: '1102'
        pg: '32'
    - query:
        rozd: 4
        bd: 1
        rd: '1102'
        pg: '02'
    _code: '110239'
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1302'
        coef: 0.50
    _code: '130299'
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1303'
        pg: '01'
        coef: 0.25
    _code: '130399'
  - row:
    - query:
        bd: 1
        rd: '1404'
    _code: '140400'
  - row:
    - query:
        rozd: 4
        bd: 1
        rd: '2201'
        pg: '11'
    - query:
        bd: 1
        rd: '2201'
        pg: '09'
    _code: '220100'
    # Единый налог 
    # Криворожский район 
  - row:
    - query:
        rozd: 5
        bd: 1
        rd: '1805'
        pg: '01'
        coef: 0.43
    - query:
        rozd: 4
        bd: 1
        rd: '1805'
        pg: '03'
    - query:
        rozd: 1
        bd: 1
        rd: '1805'
        pg: '03'
    _code: '180501'
  - row:
    - query:
        rozd: 5
        bd: 1
        rd: '1805'
        pg: '02'
        coef: 0.43
    - query:
        rozd: 1
        bd: 1
        rd: '1805'
        pg: '04'
    - query:
        rozd: 4
        bd: 1
        rd: '1805'
        pg: '04'
    _code: '180502'
  - row:
    - query:
        raj: 18
        rozd: 1
        bd: 1
        rd: '1801'
        pg: '01'
    - query:
        raj: 18
        rozd: 1
        bd: 1
        rd: '1801'
        pg: '04'
    - query:
        raj: 83
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '04'
    - query:
        raj: 87
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '04'
    - query:
        raj: 83
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '01'
    - query:
        raj: 87
        rozd: 4
        bd: 1
        rd: '1801'
        pg: '01'
    _code: '180100'
  - row:
    - query:
        bd: 1
        rd: '3101'
    _code: "310199"
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1901'
        coef: 0.80
    _code: "190199"
    # ІНШІ МІСЦЕВІ
  - row:
    - query:
        bd: 1
        rd: '2101'
        pg: '03'
    - query:
        bd: 1
        rd: '2108'
        pg: '09'
    - query:
        bd: 1
        rd: '2108'
        pg: '11'
    - query:
        bd: 1
        rd: '2108'
        pg: '14'
    - query:
        bd: 1
        rd: '2406'
        pg: '03'
    - query:
        bd: 1
        rd: '1601'
    # начало бывших патентов
    - query:
        rozd: 1
        bd: 1
        rd: '1804'
    - query:
        rozd: 4
        bd: 1
        rd: '1804'
        pg: '15'
    # 0418
    - query:
        rozd: 2
        bd: 1
        rd: '1804'
        pg: '15'
    _code: '240600'
  # конец бывших патентов
  # Дополнительно для м/б
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1901'
        coef: 0.25
    _code: '190177'
  - row:
    - query:
        rozd: 3
        bd: 0
        rd: '1101'
        coef: 0.60
    _code: '110177'
  - row:
    - query:
        rozd: 1
        bd: 1
        rd: '2108'
        pg: '11'
    _code: '210877'